# Generated by Django 3.2.8 on 2022-03-24 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='file_extension',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='image',
            name='filename',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='image',
            name='image_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='image',
            name='resolution',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='image',
            name='size',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='image',
            name='timestamp',
            field=models.CharField(default='', max_length=100),
        ),
    ]
